### ISSUE TITLE
[Task] Redesign Grafana Dashboard

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-grafana-dashboard#11]
The Grafana Dashboard has't been updated and needs redesigning to support new events. Here are some of the things to look into:
- [x] Categorize panels according to events. This will be easier for extension.
- [x] Fix unit display.
- [x] Larger default time frame.
- [x] Rename dashboard to `Cryostat` or probably the recording name #2 
- [x] Clean up unused fields (i.e. hashKey generated by Grafana)
- [x] Support separate dashboard with filters for jdk.ObjectAllocationSample
- [x] Each "sub" dashboard should have direct link back to the Main Dashboard.
- [x] Dashboard should default to open main Cryostat Dashboard on launch.

**Datasource task:**
- [ ] https://github.com/cryostatio/jfr-datasource/issues/128
- [ ] https://github.com/cryostatio/jfr-datasource/issues/62
- [ ] https://github.com/cryostatio/jfr-datasource/issues/129
- [ ] https://github.com/cryostatio/jfr-datasource/issues/130
- [ ] https://github.com/cryostatio/jfr-datasource/issues/78
- [ ] https://github.com/cryostatio/jfr-datasource/issues/134

**Comment by tthvo** [comment]
Here is my latest design:

**Grafana image**: `quay.io/thvo/cryostat-grafana-dashboard:redesign`

**Source**: [`Dashboard.json.txt`](https://github.com/cryostatio/cryostat-grafana-dashboard/files/9620783/Dashboard.json.txt)

I could not include a screenshot since the Dashboard does not fit into a single screen. Category might not be entirely accurate. Any thoughts on this @andrewazores?

**Comment by andrewazores** [comment]
The layout looks nice, I like it. The different categories are a good idea to make this more extensible in the future.

Should I still be able to see data on this new layout right now? I tried it out with a sample recording and everything is empty.

**Comment by tthvo** [comment]
Great! I will go on to the filter issues. And yes, I think so! It showed on my end. Not sure why not there?

**Comment by andrewazores** [comment]
Oh, yea, the timeframe was just way out of whack. Wonder why that is? I had to click the "zoom out" button several times to get the data within visible range and then zoom back in on it.

**Comment by andrewazores** [comment]
![image](https://user-images.githubusercontent.com/3787464/191809861-91b1b965-f7be-4687-be43-53645d11287d.png)
![image](https://user-images.githubusercontent.com/3787464/191809896-65015ccb-1883-4bd4-8a4c-eb1538a5c192.png)
![image](https://user-images.githubusercontent.com/3787464/191809935-71057bb5-58f2-44c1-948c-67797b5e35da.png)
[recording.zip](https://github.com/cryostatio/cryostat-grafana-dashboard/files/9628012/recording.zip)

Here's a sample recording and what the dashboard looks like when it's loaded. Looks great! Though I can't help but notice that my physical memory usage is ~23 PETAbytes :D

**Comment by tthvo** [comment]
> Oh, yea, the timeframe was just way out of whack. Wonder why that is? I had to click the "zoom out" button several times to get the data within visible range and then zoom back in on it.

Right I think it was my setup in the dashboard that set the overall time to ()

```json
  "time": {
    "from": "2022-09-21T18:32:04.907Z",
    "to": "2022-09-21T19:07:14.062Z"
  },
```
I should remove this when done tho :D

> Here's a sample recording and what the dashboard looks like when it's loaded. Looks great! Though I can't help but notice that my physical memory usage is ~23 PETAbytes :D

Right! I think we have not checked unit conversion in datasource. Not sure if the library converts all to bytes but my guess now is probably not, seeing this. Related to https://github.com/cryostatio/jfr-datasource/issues/129

**Comment by tthvo** [comment]
See original comments: https://github.com/cryostatio/jfr-datasource/issues/62#issuecomment-1255409007

Current look for overall panel for `Object.AllocationSample` event:

![Screenshot from 2022-09-23 03-30-33](https://user-images.githubusercontent.com/68053619/191948660-2d3a5358-507b-4911-be78-1542ab38e186.png)
![Screenshot from 2022-09-23 03-36-52](https://user-images.githubusercontent.com/68053619/191948662-20bfb2af-ce7a-41d9-8343-138fa6b32c42.png)

A Dashboard for `Object.AllocationSample` event (screen-cast):

[Screencast from 09-23-2022 07:09:40 AM.webm](https://user-images.githubusercontent.com/68053619/191948360-9c9730c4-6416-48cb-bf2c-eaa213069b59.webm)

**Comment by tthvo** [comment]
I still need to correct the units and add link in original full panel to this new more granular dashboard. Seems like adding a link on panel requires url, which fortunately allows omitting host:port parts. Though, the path seems auto-generated. Maybe, we could preconfigure the path somehow. What do you think?

**Comment by andrewazores** [comment]
Oh, by "omitting host:port parts" I think you mean a relative URL is OK, right? As in no `scheme://user@host:port` is needed, the link can be just `/some/path?query#fragment`?

**Comment by andrewazores** [comment]
https://grafana.com/docs/grafana/latest/administration/provisioning/#reusable-dashboard-urls

https://github.com/cryostatio/cryostat-grafana-dashboard/blob/a2b63e81332b0877bd08cbf713f2a738534a08a6/dashboard.json#L1801

I think what this is saying is that if we just set this `uid` property on the dashboard definitions then the path to them is statically known, not randomly generated by the instance. Then we can just assume a relative URL between the two dashboards.

**Comment by tthvo** [comment]
> https://grafana.com/docs/grafana/latest/administration/provisioning/#reusable-dashboard-urls
> 
> https://github.com/cryostatio/cryostat-grafana-dashboard/blob/a2b63e81332b0877bd08cbf713f2a738534a08a6/dashboard.json#L1801
> 
> I think what this is saying is that if we just set this `uid` property on the dashboard definitions then the path to them is statically known, not randomly generated by the instance. Then we can just assume a relative URL between the two dashboards.

Ah niceee! Then, that makes sense! Then the process should be much simpler. Thanks for explaining this. I will finish some final touches.
