### ISSUE TITLE
[Epic] Move away from `grafana-simple-json-datasource`

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-grafana-dashboard#25]
https://grafana.com/grafana/plugins/grafana-simple-json-datasource/

https://grafana.com/grafana/plugins/grafana-simple-json-datasource/

We currently use this plugin to link the `jfr-datasource` and Grafana dashboards together. This datasource plugin is no longer maintained and we need to build it separately, include it overlaid on top of the Grafana container image, and set an environment variable to get the dashboard to register the plugin. There are alternate plugins that could possibly be used instead, or else there seems to be a way to build the required functionality into the `jfr-datasource` itself.

- [x] https://github.com/cryostatio/cryostat-grafana-dashboard/issues/26
- [ ] https://github.com/cryostatio/jfr-datasource/issues/174

**Comment by andrewazores** [comment]
https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

It looks like the simple-json-datasource must be the culprit here:

![image](https://github.com/cryostatio/cryostat-grafana-dashboard/assets/3787464/e9f9933f-6782-4a63-888f-ddf7d18877a0)

This plugin will no longer work with Grafana 11+, which means our customized dashboards would also no longer work. Grafana 11 is due out this year at some point so we should get on top of finding another datasource solution in the next one or two releases.

**Comment by tthvo** [comment]
Might be useful here: https://github.com/grafana/grafana-infinity-datasource/discussions/740
