### ISSUE TITLE
[Bug] `grafana-simple-json-datasource` plugin not loaded

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-grafana-dashboard#26]
The env var `GF_INSTALL_PLUGINS=grafana-simple-json-datasource` is not set and the `grafana.ini` does not properly list the plugin location within the container image, which leads to the Grafana container not registering the plugin and not being able to communicate with the `jfr-datasource` container.

**Comment by ebaron** [comment]
Is this a false alarm? The plugin should still be installed with this line: https://github.com/cryostatio/cryostat-grafana-dashboard/blob/21a897be5bfb50fa2d7c09352519b5684c9c6572/Dockerfile#L5

**Comment by andrewazores** [comment]
Wrongly identified root cause, closing. This issue affected downstream builds but not upstream.
